create table if not exists public.leaderboard_scores (
  id bigint generated by default as identity primary key,
  player_name text not null check (char_length(trim(player_name)) between 1 and 18),
  distance integer not null check (distance >= 0 and distance <= 999999),
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists leaderboard_scores_distance_idx
  on public.leaderboard_scores (distance desc, created_at desc);

alter table public.leaderboard_scores enable row level security;

drop policy if exists "Public can read leaderboard scores" on public.leaderboard_scores;
create policy "Public can read leaderboard scores"
on public.leaderboard_scores
for select
to anon
using (true);

drop policy if exists "Public can insert leaderboard scores" on public.leaderboard_scores;
create policy "Public can insert leaderboard scores"
on public.leaderboard_scores
for insert
to anon
with check (
  char_length(trim(player_name)) between 1 and 18
  and distance >= 0
  and distance <= 999999
);
